=== luca-98/xml-learning/xsd test 1/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:element name="bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"></xs:element>
                            <xs:element name="author">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first-name" type="xs:string"/>
                                        <xs:element name="last-name" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="genre" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="price" type="xs:float"/>
                        <xs:attribute name="ISBN" type="xs:string"/>
                        <xs:attribute name="publicationdate" type="xs:date"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== luca-98/xml-learning/xsd test 1/books.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="books.xsl" ?>
<bookstore  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='books.xsd'  >
    <book price="730.54" ISBN="978-3-16-148410-0" publicationdate="2016-02-27">
        <title>The History of the Decline and Fall of the Roman Empire, Heritage Press Three Volume Set in Slipcases by Edward Gibbon</title>
        <author>
            <first-name>Edward</first-name>
            <last-name>Gibbon</last-name>
        </author>
        <genre>Classics</genre>
    </book>
    <book price="6738.774" ISBN="978-3-16-148445-0">
        <title>The Underground Railroad by Colson Whitehead</title>
        <author>
            <first-name>Colson</first-name>
            <last-name>Whitehead</last-name>
        </author>
        <genre>Classics</genre>
    </book>
    <book price="250.774" ISBN="978-3-16-121410-0">
        <title>The Little Prince : And Letter to a Hostage by Antoine de Saint-Exupery</title>
        <author>
            <first-name>Antoine</first-name>
            <last-name>de Saint-Exupery</last-name>
        </author>
        <genre>Fiction</genre>
    </book>
</bookstore>
