=== luca-98/xml-learning/xsd test 1/project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:element name="project">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string" maxOccurs="1"></xs:element>
                <xs:element name="startDate" type="xs:string" maxOccurs="1"></xs:element>
                <xs:element name="endDate" type="xs:string" maxOccurs="1"></xs:element>
                <xs:element name="manager" type="xs:string" maxOccurs="1"></xs:element>
                <xs:element name="tasks" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="task">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"></xs:element>
                                        <xs:element name="description" type="xs:string"></xs:element>
                                        <xs:element name="person" type="xs:string"></xs:element>
                                        <xs:element name="startDate" type="xs:string"></xs:element>
                                        <xs:element name="endDate" type="xs:string"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:int">
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== luca-98/xml-learning/xsd test 1/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="project.xsl"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<project xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='project.xsd'>
    <name>Phát triển phần mềm nhân sự</name>
    <startDate>2019-01-22</startDate>
    <endDate>2019-03-22</endDate>
    <manager>Nguyễn Hùng Cường</manager>
    <tasks>
        <task id='1'>
            <name>Khảo sát</name>
            <description>Khảo sát và thu thập yêu cầu khách hàng</description>
            <person>Nguyen Viet Hung</person>
            <startDate>2019-01-22</startDate>
            <endDate>2019-01-25</endDate>
        </task>
    </tasks>
    <tasks>
        <task id='2'>
            <name>Phân tích</name>
            <description>Phân tích yêu cầu</description>
            <person>Hoàng Lan Anh</person>
            <startDate>2019-01-26</startDate>
            <endDate>2019-02-05</endDate>
        </task>
    </tasks>
    <tasks>
        <task id='3'>
            <name>Thiết kế</name>
            <description>Thiết kế kiến trúc</description>
            <person>Bùi Hoàng Việt</person>
            <startDate>2019-02-07</startDate>
            <endDate>2019-02-15</endDate>
        </task>
    </tasks>
    <tasks>
        <task id='4'>
            <name>Thiết kế</name>
            <description>Thiết kế cơ sở dữ liệu</description>
            <person>Nguyễn Thế Hiển</person>
            <startDate>2019-02-08</startDate>
            <endDate>2019-02-15</endDate>
        </task>
    </tasks>
    <tasks>
        <task id='5'>
            <name>Thiết kế</name>
            <description>Thiết kế chi tiết</description>
            <person>Lâm Thế Hải</person>
            <startDate>2019-02-16</startDate>
            <endDate>2019-02-28</endDate>
        </task>
    </tasks>
    <tasks>
        <task id='6'>
            <name>Lập trình</name>
            <description>Lập trình các chức năng theo thiết kế</description>
            <person>Trần Hoàng Lân</person>
            <startDate>2019-03-01</startDate>
            <endDate>2019-03-20</endDate>
        </task>
    </tasks>
</project>
