=== luca-98/xml-learning/sample_asg1/person.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="person_list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="gender">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="(Male|Female)"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="contact">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="phone">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[0-9]{10}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="email">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[^@]+@[^\.]+\..+"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="address" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="P[0-9]{3}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== luca-98/xml-learning/sample_asg1/person.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<person_list
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='person.xsd'>
    <person id="P001">
        <name>Bui Viet Hoang</name>
        <gender>Male</gender>
        <contact>
            <phone>0984323543</phone>
            <email>hoangbv@gmail.com</email>
            <address>Xuan Dinh - Tu Liem - Ha Noi</address>            
        </contact>
    </person>
    <person id="P002">
        <name>Le Lan Huong</name>
        <gender>Female</gender>
        <contact>
            <phone>0913783232</phone>
            <email>huongll@gmail.com</email>
            <address>Duc Ly - Ly Nhan - Ha Nam</address> 
        </contact>
    </person>
    <person id="P003">
        <name>Tran Khac Minh</name>
        <gender>Male</gender>
        <contact>
            <phone>0387232331</phone>
            <email>minhtk@gmail.com</email>
            <address>Tho Loc - Hoang Hoa - Thanh Hoa</address>            
        </contact>
    </person>
    <person id="P004">
        <name>Luong Thu Ha</name>
        <gender>Female</gender>
        <contact>
            <phone>0912384234</phone>
            <email>haxinh@gmail.com</email>
            <address>Phu Dien - Nam Tu Liem - Ha Noi</address>            
        </contact>
    </person>
    <person id="P005">
        <name>Hoang Lan Anh</name>
        <gender>Female</gender>
        <contact>
            <phone>0912998323</phone>
            <email>lananh@gmail.com</email>
            <address>Tu Xa - Lam Thao - Phu Tho</address>            
        </contact>
    </person>
</person_list>
